Repository traPtitech/trap-collection-launcher, pull requests merged in 2021-12, with the labels that each got.

#44 postLauncherLoginの返り値を変更
  src/index.d.ts
  src/lib/axios.ts
  src/lib/ipc/handler/APIHandler.ts
  src/preload/preload.ts
Labels: enhancement

#45 fetchまわりの実装
  src/index.d.ts
  src/lib/ipc/handler/fetchGame.ts
  src/lib/ipc/ipcListener.ts
  src/preload/preload.ts
Labels: enhancement

#40 アンケート、ホームページハンドラの実装とpostLauncherHandlerの返り値を変更
  src/config.ts
  src/index.d.ts
  src/lib/ipc/handler/APIHandler.ts
  src/lib/ipc/handler/openWebPage.ts
  src/lib/ipc/handler/openWebPageHandler.ts
  src/lib/ipc/ipcListen.ts
  src/preload/preload.ts
  src/renderer/views/GameDetail/index.tsx
  webpack.renderer.config.js
Labels: enhancement

#103 macで表示されない問題修正
  .husky/pre-commit
  src/lib/main.ts
Labels: bug

#106 Change store type
  docs/openapi.yml
  package.json
  src/index.d.ts
  src/lib/axios.ts
  src/lib/fetch.ts
  src/lib/ipc/handler/APIHandler.ts
  src/lib/ipc/handler/getGameInfoHandler.ts
  src/lib/ipc/handler/getProductKeyHandler.ts
  src/lib/ipc/handler/getSeatIdHandler.ts
  src/lib/ipc/handler/getSeatVersionHandler.ts
  src/lib/ipc/handler/launchHandler.ts
  src/lib/ipc/handler/openWebPage.ts
  src/lib/ipc/handler/resetProductKetHandler.ts
  src/lib/ipc/handler/setProductKeyHandler.ts
  src/lib/ipc/handler/setSeatIdHandler.ts
  src/lib/ipc/handler/setSeatVersionHandler.ts
  src/lib/ipc/handler/sitDownHandler.ts
  src/lib/ipc/handler/sitUpHandler.ts
  src/lib/store.ts
  src/lib/typescript-axios/api.ts
  src/lib/utils/generatePaths.ts
  src/lib/utils/promiseFilter.ts
  src/lib/utils/promiseSome.ts
  src/renderer/components/Slider/index.tsx
  src/renderer/views/GameSelect/description.tsx
  src/renderer/views/GameSelect/index.tsx
  tsconfig.json
Labels: bug, enhancement
